name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .

      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3

      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write  
    steps:
    - uses: actions/checkout@v4
    - uses: kojoru/prepare-pipenv@v1
    - name: building wheel
      run: |
        pipenv install twine
        pipenv install build
        pipenv --venv
        python -m build 
        twine check dist/*
        twine upload -r testpypi dist/*
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1